plugins {
    id "io.freefair.lombok" version "9.0.0" apply false
}

allprojects {
    repositories { mavenCentral() }
}

subprojects {
    apply plugin: "java"
    apply plugin: "io.freefair.lombok"

    java {
        modularity.inferModulePath = true
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
}
