plugins { id "java" }

subprojects {
    apply plugin: "java"

    repositories { mavenCentral() }

    java {
        modularity.inferModulePath = true
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    dependencies {
        compileOnly "org.projectlombok:lombok:1.18.42"
        annotationProcessor "org.projectlombok:1.18.42"
    }
}
