plugins { id "application" }

dependencies {
    implementation project(":service")
    implementation project(":domain")

    implementation 'com.formdev:flatlaf:3.6.2'
    implementation 'com.formdev:flatlaf-extras:3.6.2'
    implementation "com.github.weisj:jsvg:2.0.0"

    implementation 'com.fifesoft:rsyntaxtextarea:3.6.0'
    implementation 'com.fifesoft:rstaui:3.3.1'
    //implementation 'com.fifesoft:autocomplete:3.3.2'

    implementation 'com.github.kwhat:jnativehook:2.2.2'
}

application {
    mainModule = "xyz.toway.notes.ui"
    mainClass = "xyz.toway.notes.ui.Main"
}
