plugins { id "application" }

dependencies {
    implementation project(":service")
    implementation project(":domain")

    implementation 'com.formdev:flatlaf:3.6.2'
    implementation 'com.formdev:flatlaf-extras:3.6.2'
}

application {
    mainModule = "xyz.toway.notes.ui"
    mainClass = "xyz.toway.notes.ui.Main"
}
