package xyz.toway.notes.ui.view;

import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import com.formdev.flatlaf.icons.FlatSearchWithHistoryIcon;
import xyz.toway.notes.ui.presenter.MainPresenter;
import xyz.toway.notes.ui.view.components.ListItem;

import javax.swing.*;
import java.awt.*;
import java.util.List;

public class MainForm implements GeneralView<MainPresenter> {

    private final MainPresenter presenter;

    private JPanel mainPanel;
    private JPanel leftPanel;

    public MainForm(MainPresenter presenter) {
        this.presenter = presenter;
        presenter.setView(this);
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

    private void createUIComponents() {
        mainPanel = new JPanel(new BorderLayout(8, 8));
        //leftPanel = new GroupsMenuPanel();
        //leftPanel.setPreferredSize(new Dimension(200, 0));
        //mainPanel.add(leftPanel, BorderLayout.WEST);

        // Left sidebar
        JPanel sidebar = new JPanel(new BorderLayout());
        sidebar.setBackground(Color.PINK);
        sidebar.setPreferredSize(new Dimension(200, 0));
        sidebar.setMinimumSize(new Dimension(200, 0));

        //----------
        /*List<ListItem> items = List.of(
                new ListItem("Document", "Last modified today", UIManager.getIcon("FileView.fileIcon")),
                new ListItem("Picture", "JPEG image, 1.2MB", UIManager.getIcon("FileView.directoryIcon")),
                new ListItem("Music", "MP3, 3:45 min", UIManager.getIcon("FileView.computerIcon"))
        );

        JList<ListItem> list = new JList<>(items.toArray(new ListItem[0]));
        list.setCellRenderer(new CustomListCellRenderer());
        list.setFixedCellHeight(44); // More space for two lines*/

        sidebar.add(new JScrollPane(getSidebarMenuList()));
        //----------

        // Main content
        JPanel content = new JPanel(new BorderLayout());
        content.add(new JLabel("Main content area", SwingConstants.CENTER), BorderLayout.CENTER);
        content.setMinimumSize(new Dimension(400, 0));

        // Split pane
        JSplitPane split = new JSplitPane(JSplitPane.HORIZONTAL_SPLIT, sidebar, content);
        split.setDividerLocation(200);           // initial
        split.setResizeWeight(0);                // give extra space to right side when resizing
        split.setContinuousLayout(true);         // live resize

        mainPanel.add(split, BorderLayout.CENTER);
    }

    public JMenuBar getMenuBar() {
        var menuBar = new JMenuBar();

        JMenu fileMenu = new JMenu("File");
        fileMenu.add(new JMenuItem("Open"));
        fileMenu.add(new JMenuItem("Exit"));
        menuBar.add(fileMenu);

        JMenu helpMenu = new JMenu("Help");
        helpMenu.add(new JMenuItem("About"));
        menuBar.add(helpMenu);

        return menuBar;
    }

    public JToolBar getToolbar() {

        JToolBar toolBar = new JToolBar();
        toolBar.setMargin(new Insets(3, 3, 3, 3));

        JButton forwardButton = new JButton();
        forwardButton.setToolTipText("Forward");
        forwardButton.setIcon(new FlatSVGIcon("icons/copy.svg"));
        toolBar.add(forwardButton);
        toolBar.addSeparator();

        toolBar.add(Box.createHorizontalGlue());
        toolBar.add(getSearchField());

        return toolBar;
    }

    private JTextField getSearchField() {
        JButton searchHistoryButton = new JButton(new FlatSearchWithHistoryIcon(true));
        searchHistoryButton.setToolTipText("Search History");
        searchHistoryButton.addActionListener(e -> {
            JPopupMenu popupMenu = new JPopupMenu();
            popupMenu.add("(empty)");
            popupMenu.show(searchHistoryButton, 0, searchHistoryButton.getHeight());
        });

        JTextField searchField = new JTextField();
        searchField.putClientProperty(FlatClientProperties.TEXT_FIELD_SHOW_CLEAR_BUTTON, true);
        searchField.putClientProperty(FlatClientProperties.TEXT_FIELD_LEADING_COMPONENT, searchHistoryButton);

        Dimension pref = searchField.getPreferredSize();
        pref.width = 250;
        searchField.setPreferredSize(pref);
        searchField.setMaximumSize(pref);

        return searchField;
    }

    private JList<ListItem> getSidebarMenuList() {
        List<ListItem> items = List.of(
                new ListItem("Favorites", UIManager.getIcon("FileView.fileIcon")),
                new ListItem("Recycle Bin", UIManager.getIcon("FileView.directoryIcon")),
                new ListItem("Music", UIManager.getIcon("FileView.computerIcon"))
        );

        JList<ListItem> list = new JList<>(items.toArray(new ListItem[0]));
        list.setFixedCellHeight(28);
        list.setCellRenderer(new IconTextCellRenderer());
        return list;
    }

    @Override
    public MainPresenter getPresenter() {
        return presenter;
    }

    static class IconTextCellRenderer extends DefaultListCellRenderer {
        @Override
        public Component getListCellRendererComponent(
                JList<?> list, Object value, int index, boolean isSelected, boolean cellHasFocus) {

            JLabel label = (JLabel) super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);

            if (value instanceof ListItem item) {
                label.setText(item.getTitle());
                label.setIcon(item.getIcon());
            }
            return label;
        }
    }
}
